# Generated by Django 4.2.16 on 2026-09-04 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='play_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
