# Generated by Django 4.2.16 on 2026-08-22 03:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('total_spins', models.IntegerField(default=0)),
                ('total_bet', models.FloatField(default=0.0)),
                ('total_win', models.FloatField(default=0.0)),
            ],
            options={
                'db_table': 'game_sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='SpinHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bet', models.FloatField()),
                ('win', models.FloatField(default=0.0)),
                ('balance_before', models.FloatField()),
                ('balance_after', models.FloatField()),
                ('result', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spins', to='games.game')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spins', to='gameplay.gamesession')),
            ],
            options={
                'db_table': 'spin_history',
                'ordering': ['-created_at'],
            },
        ),
    ]
